//Objeto que aloja todos los enlaces de las imagenes
export const galeriaSrc = {
    ultramarina: {
        imagenes: {
            imgSrc1: '../recursos/Mas_detalles/Ultramarina/Imagenes/1.jpg',
            imgSrc2: '../recursos/Mas_detalles/Ultramarina/Imagenes/2.jpg',
            imgSrc3: '../recursos/Mas_detalles/Ultramarina/Imagenes/3.jpg',
            imgSrc4: '../recursos/Mas_detalles/Ultramarina/Imagenes/4.jpg',
            imgSrc5: '../recursos/Mas_detalles/Ultramarina/Imagenes/5.jpg',
            imgSrc6: '../recursos/Mas_detalles/Ultramarina/Imagenes/6.jpg',
            imgSrc7: '../recursos/Mas_detalles/Ultramarina/Imagenes/7.jpg',
            imgSrc8: '../recursos/Mas_detalles/Ultramarina/Imagenes/8.jpg',
            imgSrc9: '../recursos/Mas_detalles/Ultramarina/Imagenes/9.jpg',
            imgSrc10: '../recursos/Mas_detalles/Ultramarina/Imagenes/10.jpg',
            imgSrc11: '../recursos/Mas_detalles/Ultramarina/Imagenes/11.jpg',
            imgSrc12: '../recursos/Mas_detalles/Ultramarina/Imagenes/12.jpg',
            imgSrc13: '../recursos/Mas_detalles/Ultramarina/Imagenes/13.jpg',
            imgSrc14: '../recursos/Mas_detalles/Ultramarina/Imagenes/14.jpg',
            imgSrc15: '../recursos/Mas_detalles/Ultramarina/Imagenes/15.jpg',
            imgSrc16: '../recursos/Mas_detalles/Ultramarina/Imagenes/16.jpg',
            imgSrc17: '../recursos/Mas_detalles/Ultramarina/Imagenes/17.jpg',
            imgSrc18: '../recursos/Mas_detalles/Ultramarina/Imagenes/18.jpg',
            imgSrc19: '../recursos/Mas_detalles/Ultramarina/Imagenes/19.jpg',
            imgSrc20: '../recursos/Mas_detalles/Ultramarina/Imagenes/20.jpg',
            imgSrc21: '../recursos/Mas_detalles/Ultramarina/Imagenes/21.jpg',
            imgSrc22: '../recursos/Mas_detalles/Ultramarina/Imagenes/22.jpg',
            imgSrc23: '../recursos/Mas_detalles/Ultramarina/Imagenes/23.jpg',
            imgSrc24: '../recursos/Mas_detalles/Ultramarina/Imagenes/24.jpg',
            imgSrc25: '../recursos/Mas_detalles/Ultramarina/Imagenes/25.jpg',
            imgSrc26: '../recursos/Mas_detalles/Ultramarina/Imagenes/26.jpg',
            imgSrc27: '../recursos/Mas_detalles/Ultramarina/Imagenes/27.jpg',
            imgSrc28: '../recursos/Mas_detalles/Ultramarina/Imagenes/28.jpg',
            imgSrc29: '../recursos/Mas_detalles/Ultramarina/Imagenes/29.jpg',
            imgSrc30: '../recursos/Mas_detalles/Ultramarina/Imagenes/30.jpg',
            imgSrc31: '../recursos/Mas_detalles/Ultramarina/Imagenes/31.jpg',
            imgSrc32: '../recursos/Mas_detalles/Ultramarina/Imagenes/32.jpg',
            imgSrc33: '../recursos/Mas_detalles/Ultramarina/Imagenes/33.jpg',
            imgSrc34: '../recursos/Mas_detalles/Ultramarina/Imagenes/34.jpg',
            imgSrc35: '../recursos/Mas_detalles/Ultramarina/Imagenes/35.jpg',
            imgSrc36: '../recursos/Mas_detalles/Ultramarina/Imagenes/36.jpg',
            imgSrc37: '../recursos/Mas_detalles/Ultramarina/Imagenes/37.jpg',
        },
        miniaturas: {
            miniSrc1: '../recursos/Mas_detalles/Ultramarina/Miniaturas/1.jpg',
            miniSrc2: '../recursos/Mas_detalles/Ultramarina/Miniaturas/2.jpg',
            miniSrc3: '../recursos/Mas_detalles/Ultramarina/Miniaturas/3.jpg',
            miniSrc4: '../recursos/Mas_detalles/Ultramarina/Miniaturas/4.jpg',
            miniSrc5: '../recursos/Mas_detalles/Ultramarina/Miniaturas/5.jpg',
            miniSrc6: '../recursos/Mas_detalles/Ultramarina/Miniaturas/6.jpg',
            miniSrc7: '../recursos/Mas_detalles/Ultramarina/Miniaturas/7.jpg',
            miniSrc8: '../recursos/Mas_detalles/Ultramarina/Miniaturas/8.jpg',
            miniSrc9: '../recursos/Mas_detalles/Ultramarina/Miniaturas/9.jpg',
            miniSrc10: '../recursos/Mas_detalles/Ultramarina/Miniaturas/10.jpg',
            miniSrc11: '../recursos/Mas_detalles/Ultramarina/Miniaturas/11.jpg',
            miniSrc12: '../recursos/Mas_detalles/Ultramarina/Miniaturas/12.jpg',
            miniSrc13: '../recursos/Mas_detalles/Ultramarina/Miniaturas/13.jpg',
            miniSrc14: '../recursos/Mas_detalles/Ultramarina/Miniaturas/14.jpg',
            miniSrc15: '../recursos/Mas_detalles/Ultramarina/Miniaturas/15.jpg',
            miniSrc16: '../recursos/Mas_detalles/Ultramarina/Miniaturas/16.jpg',
            miniSrc17: '../recursos/Mas_detalles/Ultramarina/Miniaturas/17.jpg',
            miniSrc18: '../recursos/Mas_detalles/Ultramarina/Miniaturas/18.jpg',
            miniSrc19: '../recursos/Mas_detalles/Ultramarina/Miniaturas/19.jpg',
            miniSrc20: '../recursos/Mas_detalles/Ultramarina/Miniaturas/20.jpg',
            miniSrc21: '../recursos/Mas_detalles/Ultramarina/Miniaturas/21.jpg',
            miniSrc22: '../recursos/Mas_detalles/Ultramarina/Miniaturas/22.jpg',
            miniSrc23: '../recursos/Mas_detalles/Ultramarina/Miniaturas/23.jpg',
            miniSrc24: '../recursos/Mas_detalles/Ultramarina/Miniaturas/24.jpg',
            miniSrc25: '../recursos/Mas_detalles/Ultramarina/Miniaturas/25.jpg',
            miniSrc26: '../recursos/Mas_detalles/Ultramarina/Miniaturas/26.jpg',
            miniSrc27: '../recursos/Mas_detalles/Ultramarina/Miniaturas/27.jpg',
            miniSrc28: '../recursos/Mas_detalles/Ultramarina/Miniaturas/28.jpg',
            miniSrc29: '../recursos/Mas_detalles/Ultramarina/Miniaturas/29.jpg',
            miniSrc30: '../recursos/Mas_detalles/Ultramarina/Miniaturas/30.jpg',
            miniSrc31: '../recursos/Mas_detalles/Ultramarina/Miniaturas/31.jpg',
            miniSrc32: '../recursos/Mas_detalles/Ultramarina/Miniaturas/32.jpg',
            miniSrc33: '../recursos/Mas_detalles/Ultramarina/Miniaturas/33.jpg',
            miniSrc34: '../recursos/Mas_detalles/Ultramarina/Miniaturas/34.jpg',
            miniSrc35: '../recursos/Mas_detalles/Ultramarina/Miniaturas/35.jpg',
            miniSrc36: '../recursos/Mas_detalles/Ultramarina/Miniaturas/36.jpg',
            miniSrc37: '../recursos/Mas_detalles/Ultramarina/Miniaturas/37.jpg',
        }
    },
    occidentalis: {
        imagenes: {
            imgSrc1: '../recursos/Mas_detalles/Occidentalis/Imagenes/1.jpg',
            imgSrc2: '../recursos/Mas_detalles/Occidentalis/Imagenes/2.jpg',
            imgSrc3: '../recursos/Mas_detalles/Occidentalis/Imagenes/3.jpg',
            imgSrc4: '../recursos/Mas_detalles/Occidentalis/Imagenes/4.jpg',
            imgSrc5: '../recursos/Mas_detalles/Occidentalis/Imagenes/5.jpg',
            imgSrc6: '../recursos/Mas_detalles/Occidentalis/Imagenes/6.jpg',
            imgSrc7: '../recursos/Mas_detalles/Occidentalis/Imagenes/7.jpg',
            imgSrc8: '../recursos/Mas_detalles/Occidentalis/Imagenes/8.jpg',
            imgSrc9: '../recursos/Mas_detalles/Occidentalis/Imagenes/9.jpg',
            imgSrc10: '../recursos/Mas_detalles/Occidentalis/Imagenes/10.jpg',
            imgSrc11: '../recursos/Mas_detalles/Occidentalis/Imagenes/11.jpg',
            imgSrc12: '../recursos/Mas_detalles/Occidentalis/Imagenes/12.jpg',
            imgSrc13: '../recursos/Mas_detalles/Occidentalis/Imagenes/13.jpg',
            imgSrc14: '../recursos/Mas_detalles/Occidentalis/Imagenes/14.jpg',
            imgSrc15: '../recursos/Mas_detalles/Occidentalis/Imagenes/15.jpg',
            imgSrc16: '../recursos/Mas_detalles/Occidentalis/Imagenes/16.jpg',
            imgSrc17: '../recursos/Mas_detalles/Occidentalis/Imagenes/17.jpg',
            imgSrc18: '../recursos/Mas_detalles/Occidentalis/Imagenes/18.jpg',
            imgSrc19: '../recursos/Mas_detalles/Occidentalis/Imagenes/19.jpg',
            imgSrc20: '../recursos/Mas_detalles/Occidentalis/Imagenes/20.jpg',
            imgSrc21: '../recursos/Mas_detalles/Occidentalis/Imagenes/21.jpg',
            imgSrc22: '../recursos/Mas_detalles/Occidentalis/Imagenes/22.jpg',
            imgSrc23: '../recursos/Mas_detalles/Occidentalis/Imagenes/23.jpg',
            imgSrc24: '../recursos/Mas_detalles/Occidentalis/Imagenes/24.jpg',
            imgSrc25: '../recursos/Mas_detalles/Occidentalis/Imagenes/25.jpg',
            imgSrc26: '../recursos/Mas_detalles/Occidentalis/Imagenes/26.jpg',
            imgSrc27: '../recursos/Mas_detalles/Occidentalis/Imagenes/27.jpg',
            imgSrc28: '../recursos/Mas_detalles/Occidentalis/Imagenes/28.jpg',
            imgSrc29: '../recursos/Mas_detalles/Occidentalis/Imagenes/29.jpg',
        },
        miniaturas: {
            miniSrc1: '../recursos/Mas_detalles/Occidentalis/Miniaturas/1.jpg',
            miniSrc2: '../recursos/Mas_detalles/Occidentalis/Miniaturas/2.jpg',
            miniSrc3: '../recursos/Mas_detalles/Occidentalis/Miniaturas/3.jpg',
            miniSrc4: '../recursos/Mas_detalles/Occidentalis/Miniaturas/4.jpg',
            miniSrc5: '../recursos/Mas_detalles/Occidentalis/Miniaturas/5.jpg',
            miniSrc6: '../recursos/Mas_detalles/Occidentalis/Miniaturas/6.jpg',
            miniSrc7: '../recursos/Mas_detalles/Occidentalis/Miniaturas/7.jpg',
            miniSrc8: '../recursos/Mas_detalles/Occidentalis/Miniaturas/8.jpg',
            miniSrc9: '../recursos/Mas_detalles/Occidentalis/Miniaturas/9.jpg',
            miniSrc10: '../recursos/Mas_detalles/Occidentalis/Miniaturas/10.jpg',
            miniSrc11: '../recursos/Mas_detalles/Occidentalis/Miniaturas/11.jpg',
            miniSrc12: '../recursos/Mas_detalles/Occidentalis/Miniaturas/12.jpg',
            miniSrc13: '../recursos/Mas_detalles/Occidentalis/Miniaturas/13.jpg',
            miniSrc14: '../recursos/Mas_detalles/Occidentalis/Miniaturas/14.jpg',
            miniSrc15: '../recursos/Mas_detalles/Occidentalis/Miniaturas/15.jpg',
            miniSrc16: '../recursos/Mas_detalles/Occidentalis/Miniaturas/16.jpg',
            miniSrc17: '../recursos/Mas_detalles/Occidentalis/Miniaturas/17.jpg',
            miniSrc18: '../recursos/Mas_detalles/Occidentalis/Miniaturas/18.jpg',
            miniSrc19: '../recursos/Mas_detalles/Occidentalis/Miniaturas/19.jpg',
            miniSrc20: '../recursos/Mas_detalles/Occidentalis/Miniaturas/20.jpg',
            miniSrc21: '../recursos/Mas_detalles/Occidentalis/Miniaturas/21.jpg',
            miniSrc22: '../recursos/Mas_detalles/Occidentalis/Miniaturas/22.jpg',
            miniSrc23: '../recursos/Mas_detalles/Occidentalis/Miniaturas/23.jpg',
            miniSrc24: '../recursos/Mas_detalles/Occidentalis/Miniaturas/24.jpg',
            miniSrc25: '../recursos/Mas_detalles/Occidentalis/Miniaturas/25.jpg',
            miniSrc26: '../recursos/Mas_detalles/Occidentalis/Miniaturas/26.jpg',
            miniSrc27: '../recursos/Mas_detalles/Occidentalis/Miniaturas/27.jpg',
            miniSrc28: '../recursos/Mas_detalles/Occidentalis/Miniaturas/28.jpg',
            miniSrc29: '../recursos/Mas_detalles/Occidentalis/Miniaturas/29.jpg',
        }
    },
    melanocephalus: {

    },
    leucotis: {

    },
    mexicanus: {

    }
}