
// Buscador 

export const GET_CABANAS_DISPONIBLES = "GET_CABANAS_DISPONIBLES"
export const GET_CABANAS_DISPONIBLES_SUCCESS = "GET_CABANAS_DISPONIBLES_SUCCESS"
export const GET_CABANAS_DISPONIBLES_ERROR = "GET_CABANAS_DISPONIBLES_ERROR"